<?php

/**
 * Implements hook_mail() to define email messages.
 */
function mail_cron_mail($key, &$message, $params) {
  switch ($key) {
    case 'logs_email':
      $message['subject'] = t('Logs Content');
      $message['body'][] = t('Here are the logs contents:');
      foreach ($params['logs'] as $log) {
        $message['body'][] = t('Title: @title', ['@title' => $log->getTitle()]);
      }
      break;
  }
}

/**
 * Implements hook_cron() to send emails with all contents created in the "logs" content type.
 */
function mail_cron_cron() {
  // exit;
  $last_cron_run = \Drupal::state()->get('lastcronrun');
  $current_time = time();

  if (empty($last_cron_run) || ($current_time - $last_cron_run) >= 86400) {
    // Get all nodes of the "logs" content type.
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'logs')
      ->sort('created', 'ASC');
    $nids = $query->execute();

    if (!empty($nids)) {
      $logs = \Drupal\node\Entity\Node::loadMultiple($nids);

      $mail_params = [
        'logs' => $logs,
      ];

      // Send email.
      $to = 'kmlvenkat@gmail.com'; // Change to the actual email address.
      $language_code = \Drupal::currentUser()->getPreferredLangcode();
      $params['context'] = 'logs_email';
      \Drupal::service('plugin.manager.mail')->mail('mail_cron', 'logs_email', $to, $language_code, $mail_params);
    }

    // Update the last cron run timestamp.
    \Drupal::state()->set('lastcronrun', $current_time);
  }
}


