# Schema for the configuration files of the Config assessment module.
config_assessment.settings:
  type: config_object
  label: 'Config assessment settings'
  mapping:
    example:
      type: string
      label: 'Example'
